package cm.gmail.signin;

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;

import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class GmailSignIn {

	public static void main(String[] args) {

		System.setProperty("webdriver.chrome.driver", "E:\\Users\\lahol\\chromedriver.exe");
		
		WebDriver driver=new ChromeDriver(); 
		
		driver.get("https://mail.google.com/mail/u/0/");
		
		driver.manage().window().maximize();

	            driver.findElement(By.id("identifierId")).sendKeys("testsk123456789@gmail.com"); 

	            //driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);      

	            WebDriverWait wait=new WebDriverWait(driver, 20);               

	            driver.findElement(By.xpath("//div[@class=\"VfPpkd-RLmnJb\"]")).click();         

	            driver.manage().timeouts().implicitlyWait(50, TimeUnit.SECONDS);        

	            driver.findElement(By.xpath("//input[@name=\"password\"]")).sendKeys("test@12345");             

	            //driver.findElement(By.xpath("//span[@class='VfPpkd-vQzf8d']")).click();
	            
	            Actions ac = new Actions(driver);
	            
	            ac.sendKeys(Keys.ENTER).build().perform();
	            
	            driver.findElement(By.xpath("//div[@class=\"T-I T-I-KE L3\"]")).click();
	            
	            wait.until(ExpectedConditions.elementToBeClickable(By.id(":8y")));
	            
	            driver.findElement(By.id(":8y")).click();
	            
	            driver.findElement(By.id(":8y")).sendKeys("snehakalmegh24@gmail.com");
	            
	            wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//input[@name=\"subjectbox\"]")));
	            		
	            driver.findElement(By.xpath("//input[@name=\"subjectbox\"]")).click();
	            
	            driver.findElement(By.xpath("//input[@name=\"subjectbox\"]")).sendKeys("Auto generated mail");
	            
	            driver.findElement(By.cssSelector(".Am.Al.editable.LW-avf.tS-tW")).click();
	            
	            driver.findElement(By.cssSelector(".Am.Al.editable.LW-avf.tS-tW")).sendKeys("This is an autogenerated test mail");
	            
	            
	           driver.findElement(By.cssSelector(".T-I.J-J5-Ji.aoO.v7.T-I-atl.L3")).click();

	    }  

}
